'use client';
import { useState } from 'react';

type Year = { id:string; name:string; isCurrent:boolean; terms:{name:string}[] };
type Grade = { id:string; name:string; academicYearId:string; divisionId?:string|null };
type ClassRow = { id:string; name:string; gradeId:string; academicYearId:string };
type Division = { id:string; name:string };
type User = { id:string; name:string; role:'STUDENT'|'TEACHER'; studentNumber?:string|null };
type Data = { school:{name:string;schoolType:string}; years:Year[]; divisions:Division[]; grades:Grade[]; classes:ClassRow[] };
export default function AdminPage({initialData,initialTeachers}:{initialData:Data;initialTeachers:User[]}){
 const [data,setData]=useState<Data|null>(initialData),[teachers]=useState<User[]>(initialTeachers),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function create(form:FormData,kind:string){setError('');setMessage('');const body=Object.fromEntries(form.entries());const r=await fetch('/api/school/structure',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind,...body,sortOrder:kind==='grade'||kind==='division'?Number(body.sortOrder||0):undefined,isCurrent:body.isCurrent==='on'})});const d=await r.json();if(!r.ok){setError(d.error||'保存できませんでした。');return}setMessage('学校設定を保存しました。');location.reload()}
 async function person(form:FormData,role:'STUDENT'|'TEACHER'){setError('');setMessage('');let enrollment;if(role==='STUDENT')enrollment={academicYearId:String(form.get('academicYearId')),gradeId:String(form.get('gradeId')),classId:String(form.get('classId')),rollNumber:form.get('rollNumber')?Number(form.get('rollNumber')):undefined};const r=await fetch('/api/school/people',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({role,loginId:form.get('loginId'),name:form.get('name'),password:form.get('password'),studentNumber:form.get('studentNumber'),enrollment})});const d=await r.json();if(!r.ok){setError(d.error||'登録できませんでした。');return}setMessage(role==='STUDENT'?'生徒を登録しました。':'教師を登録しました。');location.reload()}
 const year=data?.years.find(y=>y.isCurrent)||data?.years[0];
 return <><section className="hello"><div><div className="eyebrow">SCHOOL ADMINISTRATION</div><h1>学校の設定とメンバー</h1><p>{data?.school.name||'学校'}の教育課程、年度、学級、アカウントを管理します。</p></div></section>{error&&<div className="notice error">{error}</div>}{message&&<div className="notice">{message}</div>}<div className="grid admin-grid"><article className="card admin-card"><h2>学校情報</h2><p>学校種別や校名は、学校ごとの表記に合わせて設定できます。</p><form onSubmit={e=>{e.preventDefault();void create(new FormData(e.currentTarget),'school')}}><div className="form-row"><input className="form-input" name="name" defaultValue={data?.school.name||''} placeholder="学校名" required/><input className="form-input" name="schoolType" defaultValue={data?.school.schoolType||''} placeholder="学校種別" required/></div><button className="secondary-btn">学校情報を更新</button></form></article>
 <article className="card admin-card"><h2>年度を追加</h2><p>年度ごとに在籍情報を持ち、過年度の記録を追跡します。</p><form onSubmit={e=>{e.preventDefault();void create(new FormData(e.currentTarget),'year')}}><div className="form-row"><input className="form-input" name="name" placeholder="例: 2026年度" required/><label className="muted" style={{fontSize:11,display:'flex',alignItems:'center',gap:6}}><input type="checkbox" name="isCurrent"/>現在の年度にする</label></div><div className="form-row"><input className="form-input" name="startsAt" type="date" required/><input className="form-input" name="endsAt" type="date" required/></div><button className="secondary-btn">年度を追加</button></form></article>
 <article className="card admin-card"><h2>教育段階を追加</h2><p>小学校・中学校・高校など、学校の構成に応じて設定します。</p><form onSubmit={e=>{e.preventDefault();void create(new FormData(e.currentTarget),'division')}}><div className="form-row"><input className="form-input" name="name" placeholder="例: 中学校" required/><input className="form-input" name="sortOrder" type="number" placeholder="表示順"/></div><button className="secondary-btn">教育段階を追加</button></form><p style={{marginTop:12}}>登録済み: {data?.divisions.map(d=>d.name).join(' · ')||'なし'}</p></article>
 <article className="card admin-card"><h2>学年を追加</h2><p>学年は年度とひもづきます。学年数や呼び方は学校に合わせて設定できます。</p><form onSubmit={e=>{e.preventDefault();void create(new FormData(e.currentTarget),'grade')}}><div className="form-row"><select className="form-input" name="academicYearId" required><option value="">年度を選択</option>{data?.years.map(y=><option key={y.id} value={y.id}>{y.name}{y.isCurrent?'（現在）':''}</option>)}</select><select className="form-input" name="divisionId"><option value="">教育段階（任意）</option>{data?.divisions.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></div><div className="form-row"><input className="form-input" name="name" placeholder="例: 1年" required/><input className="form-input" name="sortOrder" type="number" placeholder="表示順"/></div><button className="secondary-btn">学年を追加</button></form></article>
 <article className="card admin-card"><h2>クラスを追加</h2><p>クラス数や名称は学校の運用に合わせて設定できます。</p><form onSubmit={e=>{e.preventDefault();void create(new FormData(e.currentTarget),'class')}}><div className="form-row"><select className="form-input" name="academicYearId" required><option value="">年度を選択</option>{data?.years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select><select className="form-input" name="gradeId" required><option value="">学年を選択</option>{data?.grades.filter(g=>!year||g.academicYearId===year.id).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></div><div className="form-row"><input className="form-input" name="name" placeholder="例: A組 / 1組" required/><select className="form-input" name="homeroomTeacherId"><option value="">担任（任意）</option>{teachers.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></div><button className="secondary-btn">クラスを追加</button></form></article>
 <article className="card admin-card"><h2>教師を登録</h2><p>教師用アカウントを作成します。ログイン情報は安全な方法で共有してください。</p><form onSubmit={e=>{e.preventDefault();void person(new FormData(e.currentTarget),'TEACHER')}}><div className="form-row"><input className="form-input" name="name" placeholder="氏名" required/><input className="form-input" name="loginId" placeholder="ログインID" required/></div><div className="form-row"><input className="form-input" name="password" type="password" minLength={12} placeholder="初期パスワード（12文字以上）" required/></div><button className="secondary-btn">教師を登録</button></form></article>
 <article className="card admin-card"><h2>生徒を登録</h2><p>生徒IDは学年・クラス・出席番号と別に管理します。</p><form onSubmit={e=>{e.preventDefault();void person(new FormData(e.currentTarget),'STUDENT')}}><div className="form-row"><input className="form-input" name="name" placeholder="氏名" required/><input className="form-input" name="studentNumber" placeholder="生徒ID（任意）"/></div><div className="form-row"><input className="form-input" name="loginId" placeholder="ログインID" required/><input className="form-input" name="password" type="password" minLength={12} placeholder="初期パスワード（12文字以上）" required/></div><div className="form-row"><select className="form-input" name="academicYearId" required><option value="">年度</option>{data?.years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select><select className="form-input" name="gradeId" required><option value="">学年</option>{data?.grades.filter(g=>!year||g.academicYearId===year.id).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><select className="form-input" name="classId" required><option value="">クラス</option>{data?.classes.filter(c=>!year||c.academicYearId===year.id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="form-row"><input className="form-input" name="rollNumber" type="number" min="1" placeholder="出席番号（任意）"/></div><button className="secondary-btn">生徒を登録</button></form></article>
 <article className="card admin-card"><h2>登録状況</h2><p>現在の学校構造と、過去を含む年度一覧です。</p><div className="stack">{data?.years.map(y=><div className="activity" key={y.id}><div className="activity-icon">📅</div><div className="activity-text"><b>{y.name}{y.isCurrent?' · 現在':''}</b><p>{data.grades.filter(g=>g.academicYearId===y.id).map(g=>g.name).join('、')||'学年未登録'}</p></div></div>)}</div><p>クラス {data?.classes.length||0} · 教育段階 {data?.divisions.length||0}</p></article></div></>;
}
